import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { isAbsolute, join, normalize } from "node:path";
import type { StorageDriver } from "@/lib/storage/driver";

/**
 * Local disk, for development. Keys are generated by inspectUpload and are
 * plain hex, but the join is still guarded: a key that escapes the root would
 * turn a storage read into an arbitrary file read.
 */
export class LocalStorageDriver implements StorageDriver {
  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    if (!/^[0-9a-f]{32}$/.test(key)) throw new Error("Invalid storage key.");
    const path = normalize(join(this.root, key));
    if (!path.startsWith(normalize(this.root))) throw new Error("Invalid storage key.");
    return path;
  }

  async put(key: string, bytes: Buffer): Promise<void> {
    await mkdir(this.root, { recursive: true });
    await writeFile(this.resolve(key), bytes);
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.resolve(key));
  }

  async remove(key: string): Promise<void> {
    if (!isAbsolute(this.root)) throw new Error("Storage root must be absolute.");
    await unlink(this.resolve(key)).catch(() => undefined);
  }
}
